### PR TITLE
chore: Move path_util dependency to util project

### PR DESCRIPTION
**Pull request by ghislainbourgeois**
This is imported by many projects and pulling the older path.

### CODE REVIEW

**Comment by gab-arrobo** [comment]
Hi @ghislainbourgeois, this repo has a single GO file with a single function. Would it be better to move it to the `util` or `config5g` repo (which another tiny repo), or another "bigger" aux repo? What do you think?

**Comment by ghislainbourgeois** [comment]
I think so, I did not look too much in the code, where do you think this would fit better? The name seems to imply it is configuration related.

**Comment by gab-arrobo** [comment]
> I think so, I did not look too much in the code, where do you think this would fit better? The name seems to imply it is configuration related.

Based on the name and what it does, I am thinking that `util` or `config5g` would be the most appropriate. However, I do not like the `config5g` too much because it is also a tiny repo. I personally prefer, the `util` repo.

If you would prefer, we can merge this PR and later think where to move this function. Please let me know how you would like to proceeed

**Comment by ghislainbourgeois** [comment]
I think merging this first would help. It would let us complete the move of `path_util` and archive that project first.

**Review by gab-arrobo — APPROVED** [review]
+1 (tested changes locally using `replace` directive

**Pull request merged**
